project:
  type: website
  output-dir: docs

website:
  title: "Gourmet Cheeseburgers Across the Globe"
  navbar:
    left:
      - text: "Mini-Project 01"
        href: mp01.html
      - text: "About"
        href: about.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    number-sections: false
    code-fold: true
    code-tools: true
    df-print: paged
    embed-resources: false

editor: source
